#include "pm_std.h"
struct sm_hvK3bw18B3rv2Y2cObOXU2{size_t sm_iQHdtVCXMx80N476XkQRS0;size_t
sm_2fDLfFBw9acpeKhEeIdte2;real_T*sm_bSRXX7qJUaN0DIHWaaYhc2;};typedef struct
sm_hvK3bw18B3rv2Y2cObOXU2 sm_of0j3onauKvWjmSSvpIo_0;void
sm_core_SmRealVector_create(sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_,size_t n,real_T pm_rtvAiaZQgzgWqstgEIdKX1);void
sm_core_SmRealVector_copy(sm_of0j3onauKvWjmSSvpIo_0*sm_qZ_cQkm1rd_H40WuqsAhi1,
const sm_of0j3onauKvWjmSSvpIo_0*orig);void sm_core_SmRealVector_destroy(
sm_of0j3onauKvWjmSSvpIo_0*sm_9JsNfMLIQx0SlNuEaL4I2_);int
sm_core_SmRealVector_isEmpty(const sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_);size_t sm_core_SmRealVector_size(const
sm_of0j3onauKvWjmSSvpIo_0*sm_9JsNfMLIQx0SlNuEaL4I2_);size_t
sm_core_SmRealVector_capacity(const sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_);real_T sm_core_SmRealVector_value(const
sm_of0j3onauKvWjmSSvpIo_0*sm_9JsNfMLIQx0SlNuEaL4I2_,size_t
sm_dYWQAHvQodwoJxkVJbvZO2);void sm_core_SmRealVector_setValue(
sm_of0j3onauKvWjmSSvpIo_0*sm_9JsNfMLIQx0SlNuEaL4I2_,size_t
sm_dYWQAHvQodwoJxkVJbvZO2,real_T sm_RGllRMvIRPGkpbvuetJlO2);const real_T*
sm_core_SmRealVector_values(const sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_);real_T*sm_core_SmRealVector_nonConstValues(
sm_of0j3onauKvWjmSSvpIo_0*sm_9JsNfMLIQx0SlNuEaL4I2_);void
sm_core_SmRealVector_reserve(sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_,size_t n);void sm_core_SmRealVector_clear(
sm_of0j3onauKvWjmSSvpIo_0*sm_9JsNfMLIQx0SlNuEaL4I2_);void
sm_core_SmRealVector_pushBack(sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_,real_T pm_rtvAiaZQgzgWqstgEIdKX1);void
sm_core_SmRealVector_popBack(sm_of0j3onauKvWjmSSvpIo_0*
sm_9JsNfMLIQx0SlNuEaL4I2_);struct sm_j_FWBKmbnmV3od4rfZskI1{size_t
sm_iQHdtVCXMx80N476XkQRS0;size_t sm_2fDLfFBw9acpeKhEeIdte2;int*
sm_bSRXX7qJUaN0DIHWaaYhc2;};typedef struct sm_j_FWBKmbnmV3od4rfZskI1
sm_TQdu2_64syNDZrv6nUEbg2;void sm_core_SmIntVector_create(
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_,size_t n,int
pm_rtvAiaZQgzgWqstgEIdKX1);void sm_core_SmIntVector_copy(
sm_TQdu2_64syNDZrv6nUEbg2*sm_qZ_cQkm1rd_H40WuqsAhi1,const
sm_TQdu2_64syNDZrv6nUEbg2*orig);void sm_core_SmIntVector_destroy(
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_);int
sm_core_SmIntVector_isEmpty(const sm_TQdu2_64syNDZrv6nUEbg2*
sm_9JsNfMLIQx0SlNuEaL4I2_);size_t sm_core_SmIntVector_size(const
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_);size_t
sm_core_SmIntVector_capacity(const sm_TQdu2_64syNDZrv6nUEbg2*
sm_9JsNfMLIQx0SlNuEaL4I2_);int sm_core_SmIntVector_value(const
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_,size_t
sm_dYWQAHvQodwoJxkVJbvZO2);void sm_core_SmIntVector_setValue(
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_,size_t
sm_dYWQAHvQodwoJxkVJbvZO2,int sm_RGllRMvIRPGkpbvuetJlO2);const int*
sm_core_SmIntVector_values(const sm_TQdu2_64syNDZrv6nUEbg2*
sm_9JsNfMLIQx0SlNuEaL4I2_);int*sm_core_SmIntVector_nonConstValues(
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_);void
sm_core_SmIntVector_reserve(sm_TQdu2_64syNDZrv6nUEbg2*
sm_9JsNfMLIQx0SlNuEaL4I2_,size_t n);void sm_core_SmIntVector_clear(
sm_TQdu2_64syNDZrv6nUEbg2*sm_9JsNfMLIQx0SlNuEaL4I2_);void
sm_core_SmIntVector_pushBack(sm_TQdu2_64syNDZrv6nUEbg2*
sm_9JsNfMLIQx0SlNuEaL4I2_,int pm_rtvAiaZQgzgWqstgEIdKX1);void
sm_core_SmIntVector_popBack(sm_TQdu2_64syNDZrv6nUEbg2*
sm_9JsNfMLIQx0SlNuEaL4I2_);struct sm_hat_e7_iJkzDb9Ap1xOG9_{
sm_of0j3onauKvWjmSSvpIo_0 sm_RWlUX4_bHMfJl2YOI7yzk_;sm_TQdu2_64syNDZrv6nUEbg2
sm_pvYSvKg6VCaQD8Y1jTYMj0;};typedef struct sm_hat_e7_iJkzDb9Ap1xOG9_
sm_yO2paOTOGI7QT4odEJmK4_;void sm_core_RuntimeDerivedValuesBundle_create(
sm_yO2paOTOGI7QT4odEJmK4_*sm_oRhCE2wR3WA7Mrn_6KtBb_,size_t
sm_woe4Dy0elKAl_OhOSPJM40,size_t sm_tMj4p3AQa6NvXv6VngFVB_);void
sm_core_RuntimeDerivedValuesBundle_copy(const sm_yO2paOTOGI7QT4odEJmK4_*orig,
sm_yO2paOTOGI7QT4odEJmK4_*sm_qZ_cQkm1rd_H40WuqsAhi1);void
sm_core_RuntimeDerivedValuesBundle_destroy(sm_yO2paOTOGI7QT4odEJmK4_*
sm_oRhCE2wR3WA7Mrn_6KtBb_);void sm_core_RuntimeDerivedValuesBundle_create(
sm_yO2paOTOGI7QT4odEJmK4_*sm_oRhCE2wR3WA7Mrn_6KtBb_,size_t
sm_woe4Dy0elKAl_OhOSPJM40,size_t sm_tMj4p3AQa6NvXv6VngFVB_){
sm_core_SmRealVector_create(&sm_oRhCE2wR3WA7Mrn_6KtBb_->
sm_RWlUX4_bHMfJl2YOI7yzk_,sm_woe4Dy0elKAl_OhOSPJM40,0.0);
sm_core_SmIntVector_create(&sm_oRhCE2wR3WA7Mrn_6KtBb_->
sm_pvYSvKg6VCaQD8Y1jTYMj0,sm_tMj4p3AQa6NvXv6VngFVB_,0);}void
sm_core_RuntimeDerivedValuesBundle_copy(const sm_yO2paOTOGI7QT4odEJmK4_*orig,
sm_yO2paOTOGI7QT4odEJmK4_*sm_qZ_cQkm1rd_H40WuqsAhi1){sm_core_SmRealVector_copy
(&sm_qZ_cQkm1rd_H40WuqsAhi1->sm_RWlUX4_bHMfJl2YOI7yzk_,&orig->
sm_RWlUX4_bHMfJl2YOI7yzk_);sm_core_SmRealVector_reserve(&
sm_qZ_cQkm1rd_H40WuqsAhi1->sm_RWlUX4_bHMfJl2YOI7yzk_,
sm_core_SmRealVector_capacity(&orig->sm_RWlUX4_bHMfJl2YOI7yzk_));
sm_core_SmIntVector_copy(&sm_qZ_cQkm1rd_H40WuqsAhi1->sm_pvYSvKg6VCaQD8Y1jTYMj0
,&orig->sm_pvYSvKg6VCaQD8Y1jTYMj0);sm_core_SmIntVector_reserve(&
sm_qZ_cQkm1rd_H40WuqsAhi1->sm_pvYSvKg6VCaQD8Y1jTYMj0,
sm_core_SmIntVector_capacity(&orig->sm_pvYSvKg6VCaQD8Y1jTYMj0));}void
sm_core_RuntimeDerivedValuesBundle_destroy(sm_yO2paOTOGI7QT4odEJmK4_*
sm_oRhCE2wR3WA7Mrn_6KtBb_){sm_core_SmRealVector_destroy(&
sm_oRhCE2wR3WA7Mrn_6KtBb_->sm_RWlUX4_bHMfJl2YOI7yzk_);
sm_core_SmIntVector_destroy(&sm_oRhCE2wR3WA7Mrn_6KtBb_->
sm_pvYSvKg6VCaQD8Y1jTYMj0);}
