#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
void pm_rv_equals_rv(const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmRealVector*pm__UmJPtGaW9C9junx1RpnH_);void pm_U1h5Sl4yTxoF_YCvN9hBa1(const
PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector*
pm__UmJPtGaW9C9junx1RpnH_);void pm_TnPSeUZeYw5Wc8bvD8sl80(const PmBoolVector*
pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector*pm__UmJPtGaW9C9junx1RpnH_);void
pm_fKS8kuV7G_WhlO7CcdVnc1(const PmCharVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmCharVector*pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm___43lXp90F4bzSkAXqYfT1(
const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector*
pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm_XDtBnYqrul1zO7ccbIlmV2(const
PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector*
pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm_9IegWBFmNW3wA_0fRmj9m2(const
PmBoolVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector*
pm__UmJPtGaW9C9junx1RpnH_);int_T pm_create_real_vector_fields(PmRealVector*
pm_VmBquL1cTEkIgP0cS5pM82,size_t size,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmRealVector*pm_create_real_vector(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmRealVector*pm_ZdJ6KB36NX_7JjULh6fi72(
const PmRealVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_MgDXCYHfYCiNYyF5Ik7dF2(PmRealVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_destroy_real_vector(PmRealVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);int_T pm_create_int_vector_fields(PmIntVector*
pm_VmBquL1cTEkIgP0cS5pM82,size_t size,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmIntVector*pm_create_int_vector(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);PmIntVector*pm_pLia5sG_NxTeQbxzYtpXx_(const
PmIntVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
void pm_Rdk2CZ3CCj5T0d2uDHUZ20(PmIntVector*pm_VmBquL1cTEkIgP0cS5pM82,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_destroy_int_vector(PmIntVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_VmBquL1cTEkIgP0cS5pM82,size_t size
,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmBoolVector*pm_YZQHxvtiv5rBT_iBt45HQ_
(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_SK8Vck8jU45BIyJDK11DV_(PmBoolVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_qv4zOCjtiVRVC86eoqx06_(PmBoolVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmBoolVector*
pm_Or6MViYTj4_1rM_3pn1UZ0(const PmBoolVector*pm_VmBquL1cTEkIgP0cS5pM82,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);int_T pm_create_char_vector_fields(
PmCharVector*pm_VmBquL1cTEkIgP0cS5pM82,size_t size,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);PmCharVector*pm_VJ_YkZBOp_Ry9yis8LShD1(size_t
pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_cn_kUNHZ0hjihWokUKapj_(PmCharVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_ea51z6lAUjevRfjOCHL37_(PmCharVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);int_T
pm_nUREx2_I6_H8Z9q4fW3LX2(PmSizeVector*pm_VmBquL1cTEkIgP0cS5pM82,size_t size,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmSizeVector*pm_P_7OU_rMIBro7VhkR5sYZ0(
size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_5sJaU0uW397ggcDhUnm4m0(PmSizeVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_hU5rOc4ZvyOrVHd_MYDl_2(PmSizeVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_WlKWB9N0DUmpIlj3_4orb_(const PmSizeVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmSizeVector*pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm_IdLJ4aCFEkd1hlk5xl7aY_(
const PmSizeVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmSizeVector*
pm__UmJPtGaW9C9junx1RpnH_);size_t sm_ssci_EEfTFrTq_rye3vRhIoiyR_(const
PmBoolVector*mc_ljExW6hRw43Vg4SLQUAvT1);PmSparsityPattern*
sm_ssci_l3bhD_oRHa_f9PaYKzhiY2(const PmBoolVector*mc_K__VwF1fOaiI5mgPPJMb62,
size_t mc_gN74BbsU5wqNjkJbC9b672,size_t n);int_T pm_FBD_ZCGRyF9Zix4mvl6Ip0(
PmSparsityPattern*pm_Pc8_RQ7nsOlzNUh7aYI680,size_t pm_JhTijL0ZlABf2EhQiFVX71,
size_t pm_qYV3thKugwWwSrIbTfcS10,size_t pm_8oezoIPNG9LZPP18xVIrw_,PmAllocator*
pm_an0wiQTjdlKE72zC6FJ0a2);PmSparsityPattern*pm_create_sparsity_pattern(size_t
pm_JhTijL0ZlABf2EhQiFVX71,size_t pm_qYV3thKugwWwSrIbTfcS10,size_t
pm_8oezoIPNG9LZPP18xVIrw_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_3YYVuJb7mmfC_9_znq5yH2(PmSparsityPattern*pm_xhS7ip83N1al9vsl9z_jP2,const
PmSparsityPattern*pm_7CpwkWeWUw6deoCGAHlcg0);boolean_T
pm_F9dzGbF9bw2QlZyj3V1Gf_(const PmSparsityPattern*pm_xhS7ip83N1al9vsl9z_jP2,
const PmSparsityPattern*pm_7CpwkWeWUw6deoCGAHlcg0);PmSparsityPattern*
pm_9oMk0xBPD28NQC6egedGY2(const PmSparsityPattern*pm_PJaAk_OAdWPbuizgCm_rK1,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_s_tA_vyom56bxaGbqlGcb0(
PmSparsityPattern*pm_Pc8_RQ7nsOlzNUh7aYI680,PmAllocator*
pm_an0wiQTjdlKE72zC6FJ0a2);void pm_06dTzOwkhN7oGBM_7J2hK1(PmSparsityPattern*
pm_Pc8_RQ7nsOlzNUh7aYI680,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern*pm_OLpBo6MxIVPIjv0_z_qCc2(size_t pm_WkDzWdo3HJglufgddrvj_1,
size_t pm_Y_WQkyfqLWq4_EV8mXQjt_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern*pm_8BokEnlj2bsehUZ6VBVqc0(size_t pm_WkDzWdo3HJglufgddrvj_1,
size_t pm_Y_WQkyfqLWq4_EV8mXQjt_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern*pm_LPeaDYoYWpCMrX0FHDZrj2(size_t pm_KYlcoOk9rSSGYswizhYqZ2,
size_t n,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmSparsityPattern*
pm_Fd_reSzeOBuDPZtoIWlnj0(size_t n,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
size_t sm_ssci_EEfTFrTq_rye3vRhIoiyR_(const PmBoolVector*
mc_ljExW6hRw43Vg4SLQUAvT1){size_t sm_ssci_yrT_cAWVfAhvXNLD9hpDQ1=0;const
boolean_T*sm_ssci_PMoj19AtRoOJbEKuPG4PB0=mc_ljExW6hRw43Vg4SLQUAvT1->mX;const
boolean_T*mc_jcOSsrULtHDGKqSRz3gAT0=sm_ssci_PMoj19AtRoOJbEKuPG4PB0+
mc_ljExW6hRw43Vg4SLQUAvT1->mN;while(sm_ssci_PMoj19AtRoOJbEKuPG4PB0<
mc_jcOSsrULtHDGKqSRz3gAT0)if(*sm_ssci_PMoj19AtRoOJbEKuPG4PB0++)++
sm_ssci_yrT_cAWVfAhvXNLD9hpDQ1;return sm_ssci_yrT_cAWVfAhvXNLD9hpDQ1;}
PmSparsityPattern*sm_ssci_l3bhD_oRHa_f9PaYKzhiY2(const PmBoolVector*
mc_K__VwF1fOaiI5mgPPJMb62,size_t mc_gN74BbsU5wqNjkJbC9b672,size_t n){const
size_t sm_ssci_QG0HRuCgWHwtCqEzv_3201=sm_ssci_EEfTFrTq_rye3vRhIoiyR_(
mc_K__VwF1fOaiI5mgPPJMb62);PmSparsityPattern*mc_3fmwBoA2gfKGlaDfp8GCd1=
pm_create_sparsity_pattern(sm_ssci_QG0HRuCgWHwtCqEzv_3201,
mc_gN74BbsU5wqNjkJbC9b672,n,pm_default_allocator());int32_T*
sm_ssci_S51jjFL079S8kdC86krPC0=mc_3fmwBoA2gfKGlaDfp8GCd1->mJc;int32_T*
sm_ssci_rX2Nhyrokuq9JmnRvEAkJ1=mc_3fmwBoA2gfKGlaDfp8GCd1->mIr;const int32_T*
const sm_ssci_XaGYos7NVhW7p50GO0uFj_=sm_ssci_rX2Nhyrokuq9JmnRvEAkJ1;const
boolean_T*sm_ssci_PMoj19AtRoOJbEKuPG4PB0=mc_K__VwF1fOaiI5mgPPJMb62->mX;size_t
mc_SmSSPSQfR1qEYWsVj5ELF0,mc_OUB2pptsvtdGL_LyqpgOa0;for(
mc_OUB2pptsvtdGL_LyqpgOa0=0;mc_OUB2pptsvtdGL_LyqpgOa0<n;++
mc_OUB2pptsvtdGL_LyqpgOa0){*sm_ssci_S51jjFL079S8kdC86krPC0++=((int32_T)(
sm_ssci_rX2Nhyrokuq9JmnRvEAkJ1-sm_ssci_XaGYos7NVhW7p50GO0uFj_));for(
mc_SmSSPSQfR1qEYWsVj5ELF0=0;mc_SmSSPSQfR1qEYWsVj5ELF0<
mc_gN74BbsU5wqNjkJbC9b672;++mc_SmSSPSQfR1qEYWsVj5ELF0)if(*
sm_ssci_PMoj19AtRoOJbEKuPG4PB0++)*sm_ssci_rX2Nhyrokuq9JmnRvEAkJ1++=((int32_T)(
mc_SmSSPSQfR1qEYWsVj5ELF0));}*sm_ssci_S51jjFL079S8kdC86krPC0=((int32_T)(
sm_ssci_rX2Nhyrokuq9JmnRvEAkJ1-sm_ssci_XaGYos7NVhW7p50GO0uFj_));return
mc_3fmwBoA2gfKGlaDfp8GCd1;}
