#include "pm_std.h"
#include "mc_std.h"
const McLinearAlgebraFactory*ssc_sli_85UzFWQBhqjDw5z0Xsm3Z1(void);
#include "pm_std.h"
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);int_T pm_FBD_ZCGRyF9Zix4mvl6Ip0(
PmSparsityPattern*pm_Pc8_RQ7nsOlzNUh7aYI680,size_t pm_JhTijL0ZlABf2EhQiFVX71,
size_t pm_qYV3thKugwWwSrIbTfcS10,size_t pm_8oezoIPNG9LZPP18xVIrw_,PmAllocator*
pm_an0wiQTjdlKE72zC6FJ0a2);PmSparsityPattern*pm_create_sparsity_pattern(size_t
pm_JhTijL0ZlABf2EhQiFVX71,size_t pm_qYV3thKugwWwSrIbTfcS10,size_t
pm_8oezoIPNG9LZPP18xVIrw_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_3YYVuJb7mmfC_9_znq5yH2(PmSparsityPattern*pm_xhS7ip83N1al9vsl9z_jP2,const
PmSparsityPattern*pm_7CpwkWeWUw6deoCGAHlcg0);boolean_T
pm_F9dzGbF9bw2QlZyj3V1Gf_(const PmSparsityPattern*pm_xhS7ip83N1al9vsl9z_jP2,
const PmSparsityPattern*pm_7CpwkWeWUw6deoCGAHlcg0);PmSparsityPattern*
pm_9oMk0xBPD28NQC6egedGY2(const PmSparsityPattern*pm_PJaAk_OAdWPbuizgCm_rK1,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_s_tA_vyom56bxaGbqlGcb0(
PmSparsityPattern*pm_Pc8_RQ7nsOlzNUh7aYI680,PmAllocator*
pm_an0wiQTjdlKE72zC6FJ0a2);void pm_06dTzOwkhN7oGBM_7J2hK1(PmSparsityPattern*
pm_Pc8_RQ7nsOlzNUh7aYI680,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern*pm_OLpBo6MxIVPIjv0_z_qCc2(size_t pm_WkDzWdo3HJglufgddrvj_1,
size_t pm_Y_WQkyfqLWq4_EV8mXQjt_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern*pm_8BokEnlj2bsehUZ6VBVqc0(size_t pm_WkDzWdo3HJglufgddrvj_1,
size_t pm_Y_WQkyfqLWq4_EV8mXQjt_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern*pm_LPeaDYoYWpCMrX0FHDZrj2(size_t pm_KYlcoOk9rSSGYswizhYqZ2,
size_t n,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmSparsityPattern*
pm_Fd_reSzeOBuDPZtoIWlnj0(size_t n,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_rv_equals_rv(const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector
*pm__UmJPtGaW9C9junx1RpnH_);void pm_U1h5Sl4yTxoF_YCvN9hBa1(const PmIntVector*
pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector*pm__UmJPtGaW9C9junx1RpnH_);void
pm_TnPSeUZeYw5Wc8bvD8sl80(const PmBoolVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmBoolVector*pm__UmJPtGaW9C9junx1RpnH_);void pm_fKS8kuV7G_WhlO7CcdVnc1(const
PmCharVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmCharVector*
pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm___43lXp90F4bzSkAXqYfT1(const
PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector*
pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm_XDtBnYqrul1zO7ccbIlmV2(const
PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector*
pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm_9IegWBFmNW3wA_0fRmj9m2(const
PmBoolVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector*
pm__UmJPtGaW9C9junx1RpnH_);int_T pm_create_real_vector_fields(PmRealVector*
pm_VmBquL1cTEkIgP0cS5pM82,size_t size,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmRealVector*pm_create_real_vector(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmRealVector*pm_ZdJ6KB36NX_7JjULh6fi72(
const PmRealVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_MgDXCYHfYCiNYyF5Ik7dF2(PmRealVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_destroy_real_vector(PmRealVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);int_T pm_create_int_vector_fields(PmIntVector*
pm_VmBquL1cTEkIgP0cS5pM82,size_t size,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
PmIntVector*pm_create_int_vector(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);PmIntVector*pm_pLia5sG_NxTeQbxzYtpXx_(const
PmIntVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);
void pm_Rdk2CZ3CCj5T0d2uDHUZ20(PmIntVector*pm_VmBquL1cTEkIgP0cS5pM82,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_destroy_int_vector(PmIntVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_VmBquL1cTEkIgP0cS5pM82,size_t size
,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmBoolVector*pm_YZQHxvtiv5rBT_iBt45HQ_
(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_SK8Vck8jU45BIyJDK11DV_(PmBoolVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_qv4zOCjtiVRVC86eoqx06_(PmBoolVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmBoolVector*
pm_Or6MViYTj4_1rM_3pn1UZ0(const PmBoolVector*pm_VmBquL1cTEkIgP0cS5pM82,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);int_T pm_create_char_vector_fields(
PmCharVector*pm_VmBquL1cTEkIgP0cS5pM82,size_t size,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);PmCharVector*pm_VJ_YkZBOp_Ry9yis8LShD1(size_t
pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_cn_kUNHZ0hjihWokUKapj_(PmCharVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_ea51z6lAUjevRfjOCHL37_(PmCharVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);int_T
pm_nUREx2_I6_H8Z9q4fW3LX2(PmSizeVector*pm_VmBquL1cTEkIgP0cS5pM82,size_t size,
PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);PmSizeVector*pm_P_7OU_rMIBro7VhkR5sYZ0(
size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_5sJaU0uW397ggcDhUnm4m0(PmSizeVector*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_hU5rOc4ZvyOrVHd_MYDl_2(PmSizeVector*
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_WlKWB9N0DUmpIlj3_4orb_(const PmSizeVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmSizeVector*pm__UmJPtGaW9C9junx1RpnH_);boolean_T pm_IdLJ4aCFEkd1hlk5xl7aY_(
const PmSizeVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmSizeVector*
pm__UmJPtGaW9C9junx1RpnH_);
#include "pm_std.h"
size_t mc_KpKqaZjZ2rh3lSToFa7Oa2(const PmBoolVector*mc_ljExW6hRw43Vg4SLQUAvT1)
;void mc_KLKWK_FbEAF724qPNbehq1(const PmIntVector*mc_ykDPEcD4BuT8SJa7vuxej1,
const PmRealVector*x,const PmRealVector*mc_yS7VvSIKrGg9ddzBqHtUd_);void
mc_uJ_iGAyluQ5NndhonaPXl1(const PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmIntVector*pm__UmJPtGaW9C9junx1RpnH_,const PmIntVector*
mc_kmcnrlTt6IvFH5HSoyHe21);void mc_oT_HwSgZBfR7LPqZomt0Y0(const PmIntVector*
pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector*pm__UmJPtGaW9C9junx1RpnH_,const
PmIntVector*mc_kmcnrlTt6IvFH5HSoyHe21);void mc_mMmDjYPdSIEEQHj__7cd71(const
PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_);void mc_zYvj4jole4TnufsPoZWW_2(const
PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector*
pm__UmJPtGaW9C9junx1RpnH_,const PmBoolVector*mc_i34rFP0sHa_dTbFseidcw0);void
mc_TJe2EtJyyhfHpuJYOjxfC0(const PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmIntVector*pm__UmJPtGaW9C9junx1RpnH_,boolean_T mc_7lBL31aWjgSfMHGQtksob2);
void mc_JM1DLKwRGzo9Uyq32V72E_(const PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,
const PmIntVector*mc_MmlNWCb0Iec292kl7KbkQ1);void mc_si_irLJWyQLY_l4tqebAe_(
const PmIntVector*mc_rxT7_6KqJcx5sNYEWRALX2,int32_T mc_RGllRMvIRPGkpbvuetJlO2)
;void mc_pJmDkwzzX3Iu6_VR_MyvL_(const PmBoolVector*mc_Hf_a_gs1wyoHoosYiGonU0,
const PmBoolVector*mc_AV_LMGONnBUCahwCg3D4y_,const PmIntVector*
mc_YwEOIpm092vI_BA0rQzvJ2);void mc_SKE1EUStKD_KtRTTXrxqv2(const PmBoolVector*
mc_9_yWAFd98YjxIPCHmG5rr0,size_t mc__VPpmCt_TuqLdOtTsmwgk2,const PmBoolVector*
mc_Ds0gTsuf_v_EnBO9LqpvK_,size_t mc_947YwtWZMq1Crv_q1N3191,size_t
mc_QHNSjd8JBrVVYZAcs7Zm32);void mc_OT_v_IC_x9R85Z4eHn1jA0(const PmRealVector*
mc_9_yWAFd98YjxIPCHmG5rr0,size_t mc__VPpmCt_TuqLdOtTsmwgk2,const PmRealVector*
mc_Ds0gTsuf_v_EnBO9LqpvK_,size_t mc_947YwtWZMq1Crv_q1N3191,size_t
mc_QHNSjd8JBrVVYZAcs7Zm32);void mc_J9HotRGeuZtxiip_GSZPb0(PmRealVector*
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector*pm__UmJPtGaW9C9junx1RpnH_);size_t
mc_lp5J2bZ8EcxnhyI1PKPZd2(const PmBoolVector*mc_G15g52JPQFeDaEm_uJadW_);void
mc__xr97Mh4VU4bdE2CcyEVf_(const PmIntVector*mc_YwEOIpm092vI_BA0rQzvJ2,const
PmBoolVector*mc_AV_LMGONnBUCahwCg3D4y_);size_t mc_pdD80p5I4a4oDKki08oZ50(const
PmIntVector*mc_kI6kqxnpJaUqvLfVbMkdr0);size_t mc_a_dd0x8Rstf0HD74BJt9A2(const
PmRealVector*mc_ZxltZcnt1eSoyJTnrOm7z2);size_t mc_8u8_LRBN9SbcEOkeum7ag0(const
PmBoolVector*mc_ZxltZcnt1eSoyJTnrOm7z2);boolean_T mc_Ukc2BYyTIIZDpb_lFOWTt0(
const PmIntVector*mc_kI6kqxnpJaUqvLfVbMkdr0);boolean_T
mc_l26oJh0UM_xwSgKIeOC5J0(const PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,int32_T
mc_RGllRMvIRPGkpbvuetJlO2);boolean_T mc_ocDPr6f6C4_v9b5NDj8JH_(const
PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,real_T mc_RGllRMvIRPGkpbvuetJlO2);void
mc_fuQc8C9CyCuf_KkBLV8eb0(const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmRealVector*pm__UmJPtGaW9C9junx1RpnH_);void mc_8BTcsQ6C8h5zrW1ZQRhKf1(const
PmRealVector*x,real_T mc_ljExW6hRw43Vg4SLQUAvT1);void mc_W0fX8K54ez0qAgM9tXjsi_
(const PmRealVector*x,const PmRealVector*mc_ET9_5EAP116KvP5KVqsrD2);void
mc_fjtK_RGCYgp34_TjPN6zv1(const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmRealVector*pm__UmJPtGaW9C9junx1RpnH_);void mc_LlLyVwCApgTvSBfIvzOuk0(const
PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,real_T a,const PmRealVector*
pm__UmJPtGaW9C9junx1RpnH_);void mc_fIL9UyKjuKeUlnGmcXq5r2(const PmRealVector*x
,const PmRealVector*mc_ET9_5EAP116KvP5KVqsrD2,const PmRealVector*
mc_SheEjf_3lOXDmgzkmhMGG2);void mc_v7V5uZPqLRlsEpMCWsoMJ0(const PmRealVector*x
,const real_T a,const PmRealVector*mc_ET9_5EAP116KvP5KVqsrD2);void
mc_DnL_y_DaeSoRsDtnK0hpB1(const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const
real_T mc_8IKoYx3qsjeiwHerWlCOS1);void mc_I_W_409sg28ysFYlBfPcr_(const
PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const real_T mc_8IKoYx3qsjeiwHerWlCOS1)
;void mc_MI5F4RaYNQR7pPk1GRkvn_(const PmIntVector*pm_JMQ_js3toioP0_0hj_fm5_,
const PmIntVector*pm__UmJPtGaW9C9junx1RpnH_);void mc_lkC6x3YtrvW6L16S6aM60_(
const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector*
pm__UmJPtGaW9C9junx1RpnH_);void mc_vfuXLuRk3KtAfbvK_cTrv2(const PmRealVector*
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector*pm__UmJPtGaW9C9junx1RpnH_);void
mc_tOKZMGNlSqK650YhjgeKv0(const PmRealVector*mc_9JsNfMLIQx0SlNuEaL4I2_,real_T
mc_8IKoYx3qsjeiwHerWlCOS1);void mc_Uy10YSjkY75ViJd9dTdYI1(const PmBoolVector*
mc_9JsNfMLIQx0SlNuEaL4I2_);void mc_Rhhlgu4QH_WTKd_5kpe4I2(const PmRealVector*
mc_9JsNfMLIQx0SlNuEaL4I2_);void mc_WmHTznO_Ih_dJw_MhKtIQ1(const PmIntVector*
mc_9JsNfMLIQx0SlNuEaL4I2_,int32_T mc_RGllRMvIRPGkpbvuetJlO2);void
mc_nLc17gFNFcvBlJrwxJV4w_(const PmIntVector*mc_9JsNfMLIQx0SlNuEaL4I2_);void
mc_W7kR8viSTKC_By0UjXE_A1(const PmIntVector*mc_9JsNfMLIQx0SlNuEaL4I2_);void
mc_AQtCbBjZ792h1_Xaj_dR92(const PmBoolVector*mc_i34rFP0sHa_dTbFseidcw0,const
PmIntVector*mc_YwEOIpm092vI_BA0rQzvJ2,boolean_T mc_8IKoYx3qsjeiwHerWlCOS1);
void mc_tLxHiRii5tbHWjrunaI2i1(const PmBoolVector*mc_9JsNfMLIQx0SlNuEaL4I2_,
boolean_T mc_8IKoYx3qsjeiwHerWlCOS1);void mc_AZRifAjle326aZku91XJU2(const
PmBoolVector*mc_9JsNfMLIQx0SlNuEaL4I2_);void mc_mGD4FL6_MDLg2bdqzdpfx_(const
PmBoolVector*x,size_t mc_SmSSPSQfR1qEYWsVj5ELF0,size_t
mc_QHNSjd8JBrVVYZAcs7Zm32);void mc_x2bRmxKlHWAMEwOZuiA_62(const PmBoolVector*
pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector*pm__UmJPtGaW9C9junx1RpnH_);void
mc_eJ9VFRIFMWxO52_BT7X_C_(const PmBoolVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmBoolVector*pm__UmJPtGaW9C9junx1RpnH_);real_T mc_WJAbbKueqClxuItYQx7b61(const
PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_);real_T mc_TuU8NakpY91qxLM4is2wV2(const
PmRealVector*pm_VmBquL1cTEkIgP0cS5pM82);int32_T mc_dLmR9a64iWQBHX4QM5zCr2(
const PmIntVector*pm_VmBquL1cTEkIgP0cS5pM82);int32_T mc_eIjmwucqCUJT1PyCl_z5b_
(const PmIntVector*pm_VmBquL1cTEkIgP0cS5pM82);void mc_loSQGFba0sjWysbLdmqzS1(
PmIntVector*mc_QyVbO3pTvGiccU8Tn2eK2_,const PmIntVector*
mc_kI6kqxnpJaUqvLfVbMkdr0);void mc_O_flPmjeFB4ZmON9Xp2iV_(PmRealVector*
mc_EBUUePJ08d2hXtTa8LU0J_,const PmRealVector*mc_23nxQONnTNHWizowC7lIt0,const
PmSparsityPattern*mc_UYX2aVqEUCl0fW5_qT4Lo1);void mc_K1ezq3TzhoNUE_SEp0Dr12(
const PmRealVector*mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern*
mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_);void
mc_WuGlfcFda9zO01qKeAxMn_(const PmRealVector*pm__UmJPtGaW9C9junx1RpnH_,const
PmRealVector*mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern*
mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_);void
mc_qEYnRq0Ff87lxOQck1Gqi_(const PmRealVector*pm__UmJPtGaW9C9junx1RpnH_,const
PmRealVector*mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern*
mc_73ubi6fCtM2UVxkG602gl0,const real_T*x);void mc_SZGAWN4U4XTzc5RKGKSk5_(const
PmRealVector*pm__UmJPtGaW9C9junx1RpnH_,const PmRealVector*
mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern*mc_73ubi6fCtM2UVxkG602gl0,
const PmRealVector*mc_2cVF0Ggof80TSRmRbhE8l1,size_t mc_LMkPrnaKcsYHEp0eExPFH1)
;void mc_FoRQvfcV_dWdjx5L1lyM_0(const PmRealVector*pm__UmJPtGaW9C9junx1RpnH_,
const PmRealVector*mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern*
mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_,const
PmRealVector*mc_5LkYradW8mKeL3fLSt9By1);void mc_lBp5wbXG7AvQ3hxoerNOW_(const
PmRealVector*pm__UmJPtGaW9C9junx1RpnH_,const PmRealVector*
mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern*mc_73ubi6fCtM2UVxkG602gl0,
const PmRealVector*pm_JMQ_js3toioP0_0hj_fm5_);void mc_z041e_QXd3uR2ef2CH37s1(
const PmRealVector*mc_ET9_5EAP116KvP5KVqsrD2,const PmRealVector*
mc_0R8y9UtrLk3busEbM65xW_,const PmSparsityPattern*mc__aqwF2UeMrHkDfRgGhMkr0,
size_t mc_OUB2pptsvtdGL_LyqpgOa0,real_T mc_8IKoYx3qsjeiwHerWlCOS1);void
mc_6IsBGrycIJELSxeQVWGP02(const PmRealVector*mc_SheEjf_3lOXDmgzkmhMGG2,const
PmRealVector*x,const PmRealVector*mc_ET9_5EAP116KvP5KVqsrD2);void
mc_fDK_uVHGu_qFAztUmYrXG0(const PmRealVector*mc_Hf_a_gs1wyoHoosYiGonU0,const
PmRealVector*mc_AV_LMGONnBUCahwCg3D4y_,const PmIntVector*
mc_Ma839gzucrzsXwGyDhMa82);void mc_Pv5PxBp1nNTpA2nv2TKO50(const PmRealVector*
mc_Hf_a_gs1wyoHoosYiGonU0,const PmIntVector*mc_Ma839gzucrzsXwGyDhMa82,const
PmRealVector*mc_AV_LMGONnBUCahwCg3D4y_);void mc_57l_YQYSoo0Ro6WNuRptH_(const
PmRealVector*a,const PmIntVector*mc_SmSSPSQfR1qEYWsVj5ELF0,const PmRealVector*
b);void mc_rQYUV3yV8oYU8KnRKkDRk1(const PmRealVector*a,const PmRealVector*b,
const PmBoolVector*mc_SmSSPSQfR1qEYWsVj5ELF0);void mc_Xx__kIPwzSZkrHpStVmJF_(
const PmRealVector*a,const PmBoolVector*mc_SmSSPSQfR1qEYWsVj5ELF0,const
PmRealVector*b);void mc__oSPLVBiXeFzzJsThp3Cn_(const PmRealVector*a,const
PmBoolVector*mc_SmSSPSQfR1qEYWsVj5ELF0,real_T x);void mc_BtNbeiWJf_2ScS2FihDGI0
(const PmIntVector*mc_Fgipzm4dZtWjNvleXva_V1,const PmSparsityPattern*
mc_wgw5_klFOULlYUS4qsiDG1);void mc_rxnwynr09yoIhr_7WJOnw2(const PmBoolVector*
mc_Fgipzm4dZtWjNvleXva_V1,const PmSparsityPattern*mc_wgw5_klFOULlYUS4qsiDG1);
void mc_GXd0l4NyYg6UNbaEbfuyY1(const PmBoolVector*mc_Fgipzm4dZtWjNvleXva_V1,
const PmSparsityPattern*mc_wgw5_klFOULlYUS4qsiDG1);void
mc_0IN6lZI7UaPeQvvz13t6Z_(const PmBoolVector*mc_Fgipzm4dZtWjNvleXva_V1,const
PmSparsityPattern*mc_wgw5_klFOULlYUS4qsiDG1);void mc_jk3AE9w8Z153JpwqOK4cP_(
const PmBoolVector*mc_v4k0LG4l9Qk9hEXlOIKML_,const PmSparsityPattern*
mc_3fmwBoA2gfKGlaDfp8GCd1,const PmRealVector*mc_A1lUr3Ax9HoRb_bkcLe_A1);void
mc_PUtu_CUnyMAexj3n9ThPz1(const PmBoolVector*pm__UmJPtGaW9C9junx1RpnH_,const
PmSparsityPattern*mc_73ubi6fCtM2UVxkG602gl0,const PmBoolVector*
pm_JMQ_js3toioP0_0hj_fm5_);void mc_wMbxp0k7MHKEjpdy17fjt_(const PmRealVector*
mc_jJ78FsEfvlTthTdupUhHD2,const PmSparsityPattern*mc_3fmwBoA2gfKGlaDfp8GCd1,
const PmBoolVector*mc_ID3sxM8zmIB_ZiazgNvWq2);void mc_5PAUXWifOqPPHW3wOzFa92(
const PmRealVector*mc_jJ78FsEfvlTthTdupUhHD2,const PmSparsityPattern*
mc_3fmwBoA2gfKGlaDfp8GCd1,const PmBoolVector*pm_gq3kPpO4Hdv_0UBmX5sfB1);
PmRealVector mc_mnPo3YlQdExsVqjHael_W2(const PmRealVector*
mc_ljExW6hRw43Vg4SLQUAvT1,size_t mc_XteRrKcywHWBP4sFymZ6y0,size_t
mc_jcOSsrULtHDGKqSRz3gAT0);
#include "pm_std.h"
PmfMessageId mc_mxm21WWs6l5c_8l2dz6850(PmSparsityPattern**
mc_VcKY7m0QAr85hALPtvLmC2,PmRealVector**mc__Kvhop9nZXtclpTQDqH0K2,const
PmSparsityPattern*mc__aqwF2UeMrHkDfRgGhMkr0,const PmRealVector*
mc_0R8y9UtrLk3busEbM65xW_,PmAllocator*mc_YMfc_eB3rHMVJUig1uu500);
#include "string.h"
struct McLinearAlgebraDataTag{PmSparsityPattern*ssc_sli_J37SNUIXrn9q_Uqqr__A2_
;PmRealVector*ssc_sli_3Mhieno68tV7ISU64AdE22;PmSparsityPattern*
mc_t_6NUyOFwEImo4lDjZDMu0;};static McLinearAlgebraData*
ssc_sli_wj1ZpDNhHSArg87VW9JN4_(PmAllocator*pm_WFHqm0fOpgfhKZFbY5NWh2,const
PmSparsityPattern*ssc_sli_5o09eFtac71yuzRVtLhhP0){McLinearAlgebraData*
mc_6peHhhgu8wo0Kp3HDh_aI0=(McLinearAlgebraData*)((pm_WFHqm0fOpgfhKZFbY5NWh2)->
mCallocFcn((pm_WFHqm0fOpgfhKZFbY5NWh2),(sizeof(McLinearAlgebraData)),(1)));
mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_sli_J37SNUIXrn9q_Uqqr__A2_=
pm_9oMk0xBPD28NQC6egedGY2(ssc_sli_5o09eFtac71yuzRVtLhhP0,
pm_WFHqm0fOpgfhKZFbY5NWh2);mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_t_6NUyOFwEImo4lDjZDMu0=NULL;mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_3Mhieno68tV7ISU64AdE22=NULL;return mc_6peHhhgu8wo0Kp3HDh_aI0;}static
void ssc_sli_75HUBDvtObFMB6p0zc8hB_(McLinearAlgebraData*
mc_6peHhhgu8wo0Kp3HDh_aI0){PmAllocator*a=pm_default_allocator();if(
mc_6peHhhgu8wo0Kp3HDh_aI0->mc_t_6NUyOFwEImo4lDjZDMu0==NULL&&
mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_sli_3Mhieno68tV7ISU64AdE22==NULL){return;};
pm_06dTzOwkhN7oGBM_7J2hK1(mc_6peHhhgu8wo0Kp3HDh_aI0->mc_t_6NUyOFwEImo4lDjZDMu0
,a);pm_destroy_real_vector(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_3Mhieno68tV7ISU64AdE22,a);mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_t_6NUyOFwEImo4lDjZDMu0=NULL;mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_3Mhieno68tV7ISU64AdE22=NULL;}static McLinearAlgebraStatus
ssc_sli_ui5W6wcKUvtL1eh_QPPrI1(McLinearAlgebra*ssc_sli_hWAHcsuAg4VvIe1q1qkLx0,
const real_T*ssc_sli_gyGYov8P2mGIOhM9NpVPE1){PmAllocator*a=
pm_default_allocator();McLinearAlgebraData*mc_6peHhhgu8wo0Kp3HDh_aI0=
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mPrivateData;PmSparsityPattern*
ssc_sli_EcmOq4R3KYFY9J1LlKl_C0=NULL;PmRealVector*
ssc_sli_R5_ye_di010rXmK6rNFYj2=NULL;PmRealVector ssc_sli_z6NTgxOtJT8uVFIUX1FXa0
;PmfMessageId id;ssc_sli_75HUBDvtObFMB6p0zc8hB_(mc_6peHhhgu8wo0Kp3HDh_aI0);
ssc_sli_z6NTgxOtJT8uVFIUX1FXa0 .mN=((size_t)(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_J37SNUIXrn9q_Uqqr__A2_)->mJc[(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_J37SNUIXrn9q_Uqqr__A2_)->mNumCol]);memcpy(&(
ssc_sli_z6NTgxOtJT8uVFIUX1FXa0 .mX),&ssc_sli_gyGYov8P2mGIOhM9NpVPE1,sizeof(
real_T*));id=mc_mxm21WWs6l5c_8l2dz6850(&ssc_sli_EcmOq4R3KYFY9J1LlKl_C0,&
ssc_sli_R5_ye_di010rXmK6rNFYj2,mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_J37SNUIXrn9q_Uqqr__A2_,&ssc_sli_z6NTgxOtJT8uVFIUX1FXa0,a);if(id!=NULL)
{return MC_LA_ERROR;}mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_sli_3Mhieno68tV7ISU64AdE22
=ssc_sli_R5_ye_di010rXmK6rNFYj2;mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_t_6NUyOFwEImo4lDjZDMu0=ssc_sli_EcmOq4R3KYFY9J1LlKl_C0;return MC_LA_OK;}
static McLinearAlgebraStatus ssc_sli_g2f7Xvv85bWYhxXpjGMZ_0(McLinearAlgebra*
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0,const real_T*ssc_sli_gyGYov8P2mGIOhM9NpVPE1,
real_T*mc_ET9_5EAP116KvP5KVqsrD2,const real_T*mc_VxxeDNxb3XYZvQXh_7Mga_){
McLinearAlgebraData*mc_6peHhhgu8wo0Kp3HDh_aI0=ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->
mPrivateData;size_t ssc_sli_wpM2BH4ZgIGett_8VFoUR_=mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_t_6NUyOFwEImo4lDjZDMu0->mNumCol;size_t ssc_sli_XLDwXv2FCw6lwQmvJo2ni0=
mc_6peHhhgu8wo0Kp3HDh_aI0->mc_t_6NUyOFwEImo4lDjZDMu0->mNumRow;size_t
mc_OUB2pptsvtdGL_LyqpgOa0=0;int32_T*ssc_sli_S51jjFL079S8kdC86krPC0=
mc_6peHhhgu8wo0Kp3HDh_aI0->mc_t_6NUyOFwEImo4lDjZDMu0->mJc;int32_T*
ssc_sli_rX2Nhyrokuq9JmnRvEAkJ1=mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_t_6NUyOFwEImo4lDjZDMu0->mIr;int32_T ssc_sli_rxYOIOAUANTezy4ySs_vv1=0;real_T
ssc_sli_uL19mOBfQKQ4dbylgsvK9_=0.0;real_T*mc__lerGssn0Ru_r3kSOzEmI_=
mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_sli_3Mhieno68tV7ISU64AdE22->mX;for(
mc_OUB2pptsvtdGL_LyqpgOa0=0;mc_OUB2pptsvtdGL_LyqpgOa0<
ssc_sli_wpM2BH4ZgIGett_8VFoUR_;mc_OUB2pptsvtdGL_LyqpgOa0++){
mc_ET9_5EAP116KvP5KVqsrD2[mc_OUB2pptsvtdGL_LyqpgOa0]=0.0;}for(
mc_OUB2pptsvtdGL_LyqpgOa0=0;mc_OUB2pptsvtdGL_LyqpgOa0<
ssc_sli_wpM2BH4ZgIGett_8VFoUR_;mc_OUB2pptsvtdGL_LyqpgOa0++){
ssc_sli_uL19mOBfQKQ4dbylgsvK9_=mc_VxxeDNxb3XYZvQXh_7Mga_[
mc_OUB2pptsvtdGL_LyqpgOa0];for(ssc_sli_rxYOIOAUANTezy4ySs_vv1=
ssc_sli_S51jjFL079S8kdC86krPC0[mc_OUB2pptsvtdGL_LyqpgOa0];
ssc_sli_rxYOIOAUANTezy4ySs_vv1<ssc_sli_S51jjFL079S8kdC86krPC0[
mc_OUB2pptsvtdGL_LyqpgOa0+1];ssc_sli_rxYOIOAUANTezy4ySs_vv1++){
mc_ET9_5EAP116KvP5KVqsrD2[ssc_sli_rX2Nhyrokuq9JmnRvEAkJ1[
ssc_sli_rxYOIOAUANTezy4ySs_vv1]]+=ssc_sli_uL19mOBfQKQ4dbylgsvK9_*
mc__lerGssn0Ru_r3kSOzEmI_[ssc_sli_rxYOIOAUANTezy4ySs_vv1];}}return MC_LA_OK;}
static real_T ssc_sli_q05CIUzgkxRhwAdMdJA_y1(const McLinearAlgebra*
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0){;return 0.0;}static size_t
ssc_sli_AjN_WykJW2Qf829AQqu_M_(const PmSparsityPattern*
pm_KYlcoOk9rSSGYswizhYqZ2){return sizeof(*pm_KYlcoOk9rSSGYswizhYqZ2)+(
pm_KYlcoOk9rSSGYswizhYqZ2->mNumCol+1)*sizeof(int32_T)+((size_t)(
pm_KYlcoOk9rSSGYswizhYqZ2)->mJc[(pm_KYlcoOk9rSSGYswizhYqZ2)->mNumCol])*sizeof(
int32_T)+((size_t)(pm_KYlcoOk9rSSGYswizhYqZ2)->mJc[(pm_KYlcoOk9rSSGYswizhYqZ2)
->mNumCol])*sizeof(real_T);}static size_t ssc_sli_6HrAHJNVf7lhtUUn8fKAy2(const
McLinearAlgebra*ssc_sli_hWAHcsuAg4VvIe1q1qkLx0){const McLinearAlgebraData*
mc_6peHhhgu8wo0Kp3HDh_aI0=ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mPrivateData;return
sizeof(*ssc_sli_hWAHcsuAg4VvIe1q1qkLx0)+sizeof(*mc_6peHhhgu8wo0Kp3HDh_aI0)+
ssc_sli_AjN_WykJW2Qf829AQqu_M_(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_J37SNUIXrn9q_Uqqr__A2_)+(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_3Mhieno68tV7ISU64AdE22==NULL?0:(sizeof(*mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_3Mhieno68tV7ISU64AdE22)+mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_3Mhieno68tV7ISU64AdE22->mN*sizeof(real_T)))+(mc_6peHhhgu8wo0Kp3HDh_aI0
->mc_t_6NUyOFwEImo4lDjZDMu0==NULL?0:ssc_sli_AjN_WykJW2Qf829AQqu_M_(
mc_6peHhhgu8wo0Kp3HDh_aI0->mc_t_6NUyOFwEImo4lDjZDMu0));}static void
ssc_sli_jCI12S_6WoApmzy_icap61(McLinearAlgebra*ssc_sli_hWAHcsuAg4VvIe1q1qkLx0)
{McLinearAlgebraData*mc_6peHhhgu8wo0Kp3HDh_aI0=ssc_sli_hWAHcsuAg4VvIe1q1qkLx0
->mPrivateData;PmAllocator*a=pm_default_allocator();
ssc_sli_75HUBDvtObFMB6p0zc8hB_(mc_6peHhhgu8wo0Kp3HDh_aI0);
pm_06dTzOwkhN7oGBM_7J2hK1(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_sli_J37SNUIXrn9q_Uqqr__A2_,a);{void*ssc_sli_GAbHnJspJ6sMhe_Yzxehb_=(
mc_6peHhhgu8wo0Kp3HDh_aI0);if(ssc_sli_GAbHnJspJ6sMhe_Yzxehb_!=0){(a)->mFreeFcn
(a,ssc_sli_GAbHnJspJ6sMhe_Yzxehb_);}};{void*ssc_sli_GAbHnJspJ6sMhe_Yzxehb_=(
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0);if(ssc_sli_GAbHnJspJ6sMhe_Yzxehb_!=0){(a)->
mFreeFcn(a,ssc_sli_GAbHnJspJ6sMhe_Yzxehb_);}};}static McLinearAlgebraStatus
ssc_sli_wt_AqSjF6f64yjNsk9y_02(const McLinearAlgebraFactory*
ssc_core___8zuxSRixcOGs7OSRauz0,McLinearAlgebra**
ssc_sli_bhvtgLLFE6OQKvLokt6b82,const PmSparsityPattern*
mc_3fmwBoA2gfKGlaDfp8GCd1){PmAllocator*mc_YMfc_eB3rHMVJUig1uu500=
pm_default_allocator();McLinearAlgebra*ssc_sli_hWAHcsuAg4VvIe1q1qkLx0=(
McLinearAlgebra*)((mc_YMfc_eB3rHMVJUig1uu500)->mCallocFcn((
mc_YMfc_eB3rHMVJUig1uu500),(sizeof(McLinearAlgebra)),(1)));
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mPrivateData=ssc_sli_wj1ZpDNhHSArg87VW9JN4_(
mc_YMfc_eB3rHMVJUig1uu500,mc_3fmwBoA2gfKGlaDfp8GCd1);
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mFactor= &ssc_sli_ui5W6wcKUvtL1eh_QPPrI1;
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mSolve= &ssc_sli_g2f7Xvv85bWYhxXpjGMZ_0;
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mCondest= &ssc_sli_q05CIUzgkxRhwAdMdJA_y1;
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mMemusage= &ssc_sli_6HrAHJNVf7lhtUUn8fKAy2;
ssc_sli_hWAHcsuAg4VvIe1q1qkLx0->mDestructor= &ssc_sli_jCI12S_6WoApmzy_icap61;*
ssc_sli_bhvtgLLFE6OQKvLokt6b82=ssc_sli_hWAHcsuAg4VvIe1q1qkLx0;return MC_LA_OK;
}const McLinearAlgebraFactory*ssc_sli_85UzFWQBhqjDw5z0Xsm3Z1(void){static
McLinearAlgebraFactory ssc_core___8zuxSRixcOGs7OSRauz0;
ssc_core___8zuxSRixcOGs7OSRauz0 .mCreateLinearAlgebra= &
ssc_sli_wt_AqSjF6f64yjNsk9y_02;return&ssc_core___8zuxSRixcOGs7OSRauz0;}
