#include "pm_std.h"
typedef struct ssc_sli_gA9dQIM_7rgDQcT_NpZjO2 ssc_sli_oUrJV3_FgyyLawV_oBfPs_;
typedef struct ssc_sli_7kQzOC_3zW4oUeydbruyc1 ssc_sli_iLE7X1rVAvv2sJWqliEaz_;
typedef struct ssc_sli_33SRCRoDIn7DjhdOpdBwS2 ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1;
typedef struct ssc_sli_RFI8esRagBUcW2k8bw5eZ2 ssc_sli_6gU7USfCboRCzD6K4xA4t1;
typedef struct ssc_sli_dlYvX2_SestUBjjD0N5iJ0{ssc_sli_oUrJV3_FgyyLawV_oBfPs_*
ssc_sli__pBrrcHOM_Yfjt6fMzkfL_;ssc_sli_iLE7X1rVAvv2sJWqliEaz_*
ssc_sli_9k3t9MF_cDMi3uAvvnmOo1;}ssc_sli_G8aFZxzaBmBggFWUjuRHa_;typedef
ssc_sli_G8aFZxzaBmBggFWUjuRHa_*(*ssc_sli_9x2T4s9a4cyRce0PfMKIY_)(const
ssc_sli_oUrJV3_FgyyLawV_oBfPs_*ssc_sli_Qsb6taWGwz8FYpEsRiFvN1,const
ssc_sli_iLE7X1rVAvv2sJWqliEaz_*mc_RGllRMvIRPGkpbvuetJlO2);typedef void(*
ssc_sli_kME_13SPAYQCbUlGYp43N_)(ssc_sli_G8aFZxzaBmBggFWUjuRHa_*
ssc_sli_VXXbI_X93GG2q1tCZt11d_);typedef boolean_T(*
ssc_sli_kQKkmeUvr_Lkw14652A_u2)(const ssc_sli_oUrJV3_FgyyLawV_oBfPs_*
ssc_sli_7bAzj_TJD0HlUBq_cEnlZ1,const ssc_sli_oUrJV3_FgyyLawV_oBfPs_*
ssc_sli__nn6HKEtt87SYyNhBBszn0);typedef size_t(*ssc_sli_JTMctMZVkmoEGmaV3SPAS_
)(const ssc_sli_oUrJV3_FgyyLawV_oBfPs_*ssc_sli_Qsb6taWGwz8FYpEsRiFvN1);struct
ssc_sli_RFI8esRagBUcW2k8bw5eZ2{ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1*
mc_0TyJOxmrCFOwXODumYaSw2;ssc_sli_9x2T4s9a4cyRce0PfMKIY_
ssc_sli__KNrbYc3MbBSjqRLmvdZL0;ssc_sli_kME_13SPAYQCbUlGYp43N_
ssc_sli_ww2Op7vf7pxMNjS928Esl2;ssc_sli_kQKkmeUvr_Lkw14652A_u2
ssc_sli_9Z5gVjtdYwpO0_NEvre4B1;ssc_sli_JTMctMZVkmoEGmaV3SPAS_
ssc_sli_Y1hfLASMIWu_8YJYxx4ee0;boolean_T(*ssc_sli_HhuO89JoWfCG77nus7GWj1)(
ssc_sli_6gU7USfCboRCzD6K4xA4t1*ssc_sli_n4OAgmoqhywPhcYA74Hi62,const
ssc_sli_oUrJV3_FgyyLawV_oBfPs_*ssc_sli_Qsb6taWGwz8FYpEsRiFvN1,const
ssc_sli_iLE7X1rVAvv2sJWqliEaz_*pm_rtvAiaZQgzgWqstgEIdKX1);
ssc_sli_iLE7X1rVAvv2sJWqliEaz_*(*ssc_sli_LYHPqEuO9A_SYuY1nyU7O2)(const
ssc_sli_6gU7USfCboRCzD6K4xA4t1*ssc_sli_n4OAgmoqhywPhcYA74Hi62,const
ssc_sli_oUrJV3_FgyyLawV_oBfPs_*ssc_sli_Qsb6taWGwz8FYpEsRiFvN1);void(*
ssc_sli_xS_viAN5gCP1cUtQPigBv2)(const ssc_sli_6gU7USfCboRCzD6K4xA4t1*
ssc_sli_n4OAgmoqhywPhcYA74Hi62);void(*mc_YCFci8IAJkK9w_xpRtHta2)(
ssc_sli_6gU7USfCboRCzD6K4xA4t1*ssc_sli_n4OAgmoqhywPhcYA74Hi62);};
ssc_sli_6gU7USfCboRCzD6K4xA4t1*ssc_sli_n0Z_bxRwA__qVlhhBmWm80(size_t
ssc_sli_IDAP3dnAagwC3G3qtF_Ct0,size_t ssc_sli_579_ieTfrCf1yd5N7_9La_,
ssc_sli_9x2T4s9a4cyRce0PfMKIY_ ssc_sli_jXD1aW_OUuIrke1kPZZ5r0,
ssc_sli_kME_13SPAYQCbUlGYp43N_ ssc_sli_YGWj0CxONXrray03CHy680,
ssc_sli_kQKkmeUvr_Lkw14652A_u2 ssc_sli_9NuLAQSrZVZ_hMsgXjv5i2,
ssc_sli_JTMctMZVkmoEGmaV3SPAS_ ssc_sli_AkIfRHa2rU87dioQMiaIr_);
#include "pm_std.h"
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
#include "math.h"
struct ssc_sli_33SRCRoDIn7DjhdOpdBwS2{size_t*ssc_sli_CnZWGvlIUA7o_25OGTzTW2;
size_t ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1;ssc_sli_G8aFZxzaBmBggFWUjuRHa_**
ssc_sli_a4vENvuJLZnshJlLcawDe1;size_t ssc_sli_wqvSgxOK_lHXrHb5KCp_K1;size_t
ne_mvpp3TC9yOLyCyuveTygS0;size_t ssc_sli_SFWxCkFWeS7ZSz_FWTQIE_,
ssc_sli_DizFgb_vcx0H_k09EbgH21;boolean_T ssc_sli_ZrcR0uAjfaXUFy9IUxBOm1;};
static boolean_T ssc_sli_JOPkcdRpiVCKtu8m8072w2(ssc_sli_6gU7USfCboRCzD6K4xA4t1
*ssc_sli_n4OAgmoqhywPhcYA74Hi62,const ssc_sli_oUrJV3_FgyyLawV_oBfPs_*
ssc_sli_Qsb6taWGwz8FYpEsRiFvN1,const ssc_sli_iLE7X1rVAvv2sJWqliEaz_*
mc_RGllRMvIRPGkpbvuetJlO2){ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1*
ssc_core_SKHbY6rGfe_c5uusXTSRI1=ssc_sli_n4OAgmoqhywPhcYA74Hi62->
mc_0TyJOxmrCFOwXODumYaSw2;size_t ssc_sli_nIHOnh5_x9SNz_CZECEEY2,
ssc_sli_JfoEbsSYMLKiv6xema1Lv_;size_t ssc_sli_bIRqFrCuplgPX7MG1oPun0;boolean_T
ssc_sli_Z9gBSB2eb6sd48e8vjeXt_=false;;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_SFWxCkFWeS7ZSz_FWTQIE_++;ssc_sli_nIHOnh5_x9SNz_CZECEEY2=
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli_Y1hfLASMIWu_8YJYxx4ee0(
ssc_sli_Qsb6taWGwz8FYpEsRiFvN1)%ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1;ssc_sli_bIRqFrCuplgPX7MG1oPun0=
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_CnZWGvlIUA7o_25OGTzTW2[
ssc_sli_nIHOnh5_x9SNz_CZECEEY2];;if(ssc_sli_bIRqFrCuplgPX7MG1oPun0==((size_t)(
-1))){ssc_sli_JfoEbsSYMLKiv6xema1Lv_=ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ne_mvpp3TC9yOLyCyuveTygS0;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_CnZWGvlIUA7o_25OGTzTW2[ssc_sli_nIHOnh5_x9SNz_CZECEEY2]=
ssc_sli_JfoEbsSYMLKiv6xema1Lv_;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ne_mvpp3TC9yOLyCyuveTygS0=(ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ne_mvpp3TC9yOLyCyuveTygS0+1)%ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_wqvSgxOK_lHXrHb5KCp_K1;}else{;ssc_sli_JfoEbsSYMLKiv6xema1Lv_=
ssc_sli_bIRqFrCuplgPX7MG1oPun0;}if(ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_a4vENvuJLZnshJlLcawDe1[ssc_sli_JfoEbsSYMLKiv6xema1Lv_]!=NULL){
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli_ww2Op7vf7pxMNjS928Esl2(
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_a4vENvuJLZnshJlLcawDe1[
ssc_sli_JfoEbsSYMLKiv6xema1Lv_]);ssc_sli_Z9gBSB2eb6sd48e8vjeXt_=true;}
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_a4vENvuJLZnshJlLcawDe1[
ssc_sli_JfoEbsSYMLKiv6xema1Lv_]=ssc_sli_n4OAgmoqhywPhcYA74Hi62->
ssc_sli__KNrbYc3MbBSjqRLmvdZL0(ssc_sli_Qsb6taWGwz8FYpEsRiFvN1,
mc_RGllRMvIRPGkpbvuetJlO2);return ssc_sli_Z9gBSB2eb6sd48e8vjeXt_;}static
ssc_sli_iLE7X1rVAvv2sJWqliEaz_*ssc_sli_D_ogSJT0GpkS6G4hQPiVu_(const
ssc_sli_6gU7USfCboRCzD6K4xA4t1*ssc_sli_n4OAgmoqhywPhcYA74Hi62,const
ssc_sli_oUrJV3_FgyyLawV_oBfPs_*ssc_sli_Qsb6taWGwz8FYpEsRiFvN1){
ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1*ssc_core_SKHbY6rGfe_c5uusXTSRI1=
ssc_sli_n4OAgmoqhywPhcYA74Hi62->mc_0TyJOxmrCFOwXODumYaSw2;size_t
ssc_sli_nIHOnh5_x9SNz_CZECEEY2;size_t ssc_sli_bIRqFrCuplgPX7MG1oPun0;
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_DizFgb_vcx0H_k09EbgH21++;if(
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1==1){if(
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_CnZWGvlIUA7o_25OGTzTW2[0]!=((size_t)(
-1))){;return ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_a4vENvuJLZnshJlLcawDe1[
0]->ssc_sli_9k3t9MF_cDMi3uAvvnmOo1;}else{return NULL;}}
ssc_sli_nIHOnh5_x9SNz_CZECEEY2=ssc_sli_n4OAgmoqhywPhcYA74Hi62->
ssc_sli_Y1hfLASMIWu_8YJYxx4ee0(ssc_sli_Qsb6taWGwz8FYpEsRiFvN1)%
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1;
ssc_sli_bIRqFrCuplgPX7MG1oPun0=ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_CnZWGvlIUA7o_25OGTzTW2[ssc_sli_nIHOnh5_x9SNz_CZECEEY2];if(
ssc_sli_bIRqFrCuplgPX7MG1oPun0!=((size_t)(-1))){;;if(
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli_9Z5gVjtdYwpO0_NEvre4B1(
ssc_sli_Qsb6taWGwz8FYpEsRiFvN1,ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_a4vENvuJLZnshJlLcawDe1[ssc_sli_bIRqFrCuplgPX7MG1oPun0]->
ssc_sli__pBrrcHOM_Yfjt6fMzkfL_)){return ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_a4vENvuJLZnshJlLcawDe1[ssc_sli_bIRqFrCuplgPX7MG1oPun0]->
ssc_sli_9k3t9MF_cDMi3uAvvnmOo1;}}return NULL;}static void
ssc_sli_OjUsfumo1e1aDjsjIzcz_0(const ssc_sli_6gU7USfCboRCzD6K4xA4t1*
ssc_sli_n4OAgmoqhywPhcYA74Hi62){ssc_sli_n4OAgmoqhywPhcYA74Hi62->
mc_0TyJOxmrCFOwXODumYaSw2->ssc_sli_ZrcR0uAjfaXUFy9IUxBOm1=true;}static void
ssc_sli_4bTOBRUsG5ksIGR7SC_Mc_(ssc_sli_6gU7USfCboRCzD6K4xA4t1*
ssc_sli_n4OAgmoqhywPhcYA74Hi62){PmAllocator*a=pm_default_allocator();
ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1*ssc_core_SKHbY6rGfe_c5uusXTSRI1=
ssc_sli_n4OAgmoqhywPhcYA74Hi62->mc_0TyJOxmrCFOwXODumYaSw2;size_t
mc_SmSSPSQfR1qEYWsVj5ELF0;for(mc_SmSSPSQfR1qEYWsVj5ELF0=0;
mc_SmSSPSQfR1qEYWsVj5ELF0<ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_wqvSgxOK_lHXrHb5KCp_K1;mc_SmSSPSQfR1qEYWsVj5ELF0++){if(
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_a4vENvuJLZnshJlLcawDe1[
mc_SmSSPSQfR1qEYWsVj5ELF0]!=NULL){ssc_sli_n4OAgmoqhywPhcYA74Hi62->
ssc_sli_ww2Op7vf7pxMNjS928Esl2(ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_a4vENvuJLZnshJlLcawDe1[mc_SmSSPSQfR1qEYWsVj5ELF0]);}}{void*
ssc_sli_GAbHnJspJ6sMhe_Yzxehb_=(ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_a4vENvuJLZnshJlLcawDe1);if(ssc_sli_GAbHnJspJ6sMhe_Yzxehb_!=0){(a)->
mFreeFcn(a,ssc_sli_GAbHnJspJ6sMhe_Yzxehb_);}};{void*
ssc_sli_GAbHnJspJ6sMhe_Yzxehb_=(ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_CnZWGvlIUA7o_25OGTzTW2);if(ssc_sli_GAbHnJspJ6sMhe_Yzxehb_!=0){(a)->
mFreeFcn(a,ssc_sli_GAbHnJspJ6sMhe_Yzxehb_);}};{void*
ssc_sli_GAbHnJspJ6sMhe_Yzxehb_=(ssc_core_SKHbY6rGfe_c5uusXTSRI1);if(
ssc_sli_GAbHnJspJ6sMhe_Yzxehb_!=0){(a)->mFreeFcn(a,
ssc_sli_GAbHnJspJ6sMhe_Yzxehb_);}};{void*ssc_sli_GAbHnJspJ6sMhe_Yzxehb_=(
ssc_sli_n4OAgmoqhywPhcYA74Hi62);if(ssc_sli_GAbHnJspJ6sMhe_Yzxehb_!=0){(a)->
mFreeFcn(a,ssc_sli_GAbHnJspJ6sMhe_Yzxehb_);}};}ssc_sli_6gU7USfCboRCzD6K4xA4t1*
ssc_sli_n0Z_bxRwA__qVlhhBmWm80(size_t ssc_sli_IDAP3dnAagwC3G3qtF_Ct0,size_t
ssc_sli_579_ieTfrCf1yd5N7_9La_,ssc_sli_9x2T4s9a4cyRce0PfMKIY_
ssc_sli_jXD1aW_OUuIrke1kPZZ5r0,ssc_sli_kME_13SPAYQCbUlGYp43N_
ssc_sli_YGWj0CxONXrray03CHy680,ssc_sli_kQKkmeUvr_Lkw14652A_u2
ssc_sli_9NuLAQSrZVZ_hMsgXjv5i2,ssc_sli_JTMctMZVkmoEGmaV3SPAS_
ssc_sli_AkIfRHa2rU87dioQMiaIr_){PmAllocator*a=pm_default_allocator();
ssc_sli_6gU7USfCboRCzD6K4xA4t1*ssc_sli_n4OAgmoqhywPhcYA74Hi62=(
ssc_sli_6gU7USfCboRCzD6K4xA4t1*)((a)->mCallocFcn((a),(sizeof(
ssc_sli_6gU7USfCboRCzD6K4xA4t1)),(1)));ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1*
ssc_core_SKHbY6rGfe_c5uusXTSRI1=(ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1*)((a)->
mCallocFcn((a),(sizeof(ssc_sli_WoZ0k1KFsGjOLGSV1DBIw1)),(1)));size_t
mc_SmSSPSQfR1qEYWsVj5ELF0;;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1=ssc_sli_IDAP3dnAagwC3G3qtF_Ct0;
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_wqvSgxOK_lHXrHb5KCp_K1=
ssc_sli_579_ieTfrCf1yd5N7_9La_;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_CnZWGvlIUA7o_25OGTzTW2=(size_t*)((a)->mCallocFcn((a),(sizeof(size_t)),
(ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1)));
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_a4vENvuJLZnshJlLcawDe1=(
ssc_sli_G8aFZxzaBmBggFWUjuRHa_**)((a)->mCallocFcn((a),(sizeof(
ssc_sli_G8aFZxzaBmBggFWUjuRHa_*)),(ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_wqvSgxOK_lHXrHb5KCp_K1)));for(mc_SmSSPSQfR1qEYWsVj5ELF0=0;
mc_SmSSPSQfR1qEYWsVj5ELF0<ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_BLI7CMRxg5Fqvg1lKgAAS1;mc_SmSSPSQfR1qEYWsVj5ELF0++){
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_CnZWGvlIUA7o_25OGTzTW2[
mc_SmSSPSQfR1qEYWsVj5ELF0]=((size_t)(-1));}for(mc_SmSSPSQfR1qEYWsVj5ELF0=0;
mc_SmSSPSQfR1qEYWsVj5ELF0<ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_wqvSgxOK_lHXrHb5KCp_K1;mc_SmSSPSQfR1qEYWsVj5ELF0++){
ssc_core_SKHbY6rGfe_c5uusXTSRI1->ssc_sli_a4vENvuJLZnshJlLcawDe1[
mc_SmSSPSQfR1qEYWsVj5ELF0]=NULL;}ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ne_mvpp3TC9yOLyCyuveTygS0=0;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_SFWxCkFWeS7ZSz_FWTQIE_=0;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_DizFgb_vcx0H_k09EbgH21=0;ssc_core_SKHbY6rGfe_c5uusXTSRI1->
ssc_sli_ZrcR0uAjfaXUFy9IUxBOm1=false;ssc_sli_n4OAgmoqhywPhcYA74Hi62->
mc_0TyJOxmrCFOwXODumYaSw2=ssc_core_SKHbY6rGfe_c5uusXTSRI1;
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli__KNrbYc3MbBSjqRLmvdZL0=
ssc_sli_jXD1aW_OUuIrke1kPZZ5r0;ssc_sli_n4OAgmoqhywPhcYA74Hi62->
ssc_sli_ww2Op7vf7pxMNjS928Esl2=ssc_sli_YGWj0CxONXrray03CHy680;
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli_9Z5gVjtdYwpO0_NEvre4B1=
ssc_sli_9NuLAQSrZVZ_hMsgXjv5i2;ssc_sli_n4OAgmoqhywPhcYA74Hi62->
ssc_sli_Y1hfLASMIWu_8YJYxx4ee0=ssc_sli_AkIfRHa2rU87dioQMiaIr_;
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli_HhuO89JoWfCG77nus7GWj1=
ssc_sli_JOPkcdRpiVCKtu8m8072w2;ssc_sli_n4OAgmoqhywPhcYA74Hi62->
ssc_sli_LYHPqEuO9A_SYuY1nyU7O2=ssc_sli_D_ogSJT0GpkS6G4hQPiVu_;
ssc_sli_n4OAgmoqhywPhcYA74Hi62->ssc_sli_xS_viAN5gCP1cUtQPigBv2=
ssc_sli_OjUsfumo1e1aDjsjIzcz_0;ssc_sli_n4OAgmoqhywPhcYA74Hi62->
mc_YCFci8IAJkK9w_xpRtHta2=ssc_sli_4bTOBRUsG5ksIGR7SC_Mc_;return
ssc_sli_n4OAgmoqhywPhcYA74Hi62;}
